// Generated by scripts/generate-catalog.mjs. Do not edit.
import type { PublishedDeckContent } from './types.js';

/** 사람 승인·checksum 검증이 끝난 Free 본문만 포함하는 client-safe bundle이다. */
export const BUNDLED_FREE_DECK_CONTENT = {} as const satisfies Readonly<Record<string, PublishedDeckContent>>;
