// Generated by scripts/generate-catalog.mjs. Do not edit.
import type { PublishedDeckContent } from './types.js';

export const PUBLISHED_DECK_CONTENT = {} as const satisfies Readonly<Record<string, PublishedDeckContent>>;
