source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# RN 0.86 + Xcode 26에서 검증한 CocoaPods toolchain을 고정한다.
# CocoaPods 1.16.2는 xcodeproj >= 1.27을 요구하므로 구형 template pin을 사용하지 않는다.
gem 'cocoapods', '1.16.2'
gem 'activesupport', '>= 6.1.7.5', '< 8', '!= 7.1.0'
gem 'xcodeproj', '1.27.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
